### ISSUE TITLE
Support for 240x320 Displays

### ISSUE THREAD

**Issue by anthonyjclarke** [uklooney/AuroraDrop#2]
First of all, shoutout for this, having a lot of fun with it.... Thank you.

So, decided to see if I could get support for larger TFT displays, and of course quite straightforward with TFT_eSPI.

But, somewhere TFT Width and Height seems to be "hard coded" (or I think) for the 240x135, see below....  despite me defining these in the User_Setup file for eSPI. It works of course... but in a small window....

![image](https://user-images.githubusercontent.com/9491428/149872118-0d30676a-7907-4a3e-84b0-1793e7d16207.png)

I did try updating here, but as your comments say, they are not used!

#define TFT_PANEL_WIDTH 240     // not used currently
#define TFT_PANEL_HEIGHT 135    // not used currently

Thoughts?

**Comment by uklooney** [comment]
Hi. Sadly the current version on github doen't work great with 320x240 TFT. I have however just recently updated the project to work with 320x240 just not got round to updating github. I'll post the updates later when I get the chance.

**Comment by anthonyjclarke** [comment]
Thanks, I'll keep a lookout ;-) I did try 0.13 but causing my ESP32 to Crash on startup, had to revert to 0.12.... on my list to diagnose....

**Comment by anthonyjclarke** [comment]
Changed to a Lolin D32 and 0.13 runs... was a Lolin D32 Lite that was crashing... so will await v14 code :)

**Comment by uklooney** [comment]
Should be up now.

**Comment by anthonyjclarke** [comment]
Got it and working... love it!
